# Generated by Django 5.0 on 2023-12-25 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tag_project_end_date_project_start_date_project_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
